#!/usr/bin/env bash

BUILD_ACTIVE=true
BUILD_NAME="win32_i386_TESTNET"
BUILD_OPENSSL_VERSION="openssl/1.1.0h"
BUILD_OPTIMIZATION=""
BUILD_OPERATING_SYSTEM="win32"
BUILD_CPU="i386"
BUILD_MODE="TESTNET"
BUILD_PROJECTS=( "miner" "wallet" "wallet_classic" "daemon")